# -*- coding: utf-8 -*-
"""project1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WKwqOZPIle9LFDFxj1aJMnyA0KMgLZug
"""

from google.colab import drive
drive.mount('/content/drive')

!apt-get install sqlite3
!pip install pandas

import sqlite3
import pandas as pd
import os

conn=sqlite3.connect("my_database.db")

#define the correct path for the ddatabase
db_path="/content/drive/MyDrive/my_database.db"

db_folder="/content/drive/MyDrive/sqlfile"
os.makedirs(db_folder,exist_ok=True)
db_path=os.path.join(db_folder,"my_database.db")

conn=sqlite3.connect(db_path)
cursor=conn.cursor()
print("Data base connected at:",db_path)

"""customer Table"""

cursor.execute('''
CREATE TABLE BANK_CUSTOMERS1( customer_id INT ,
             	customer_name VARCHAR(20),
             	Address 	VARCHAR(20),
             	state_code  VARCHAR(3) ,
             	Telephone   VARCHAR(10)	);
''')
conn.commit()

def  insert_customer(customer_id,customer_name,address,state_code,telephone):
  cursor.execute("INSERT INTO BANK_CUSTOMERS1(customer_id,customer_name,address,state_code,telephone) Values(?,?,?,?,?)",(customer_id,customer_name,address,state_code,telephone))
  conn.commit()

#insert
insert_customer (123001,"Oliver", "225-5, Emeryville", "CA" , "1897614500");
insert_customer(123002,"George", "194-6,New brighton","MN" , "1897617000");
insert_customer(123003,"Harry", "2909-5,walnut creek","CA" , "1897617866");
insert_customer (123004,"Jack", "229-5, Concord",  	"CA" , "1897627999");
insert_customer(123005,"Jacob", "325-7, Mission Dist","SFO", "1897637000");
insert_customer (123006,"Noah", "275-9, saint-paul" ,  "MN" , "1897613200");
insert_customer (123007,"Charlie","125-1,Richfield",   "MN" , "1897617666");
insert_customer (123008,"Robin","3005-1,Heathrow", 	"NY" , "1897614000");

pip install tabulate

from tabulate import tabulate


# Fetch data
cursor.execute("SELECT * FROM BANK_CUSTOMERS1 ")
rows = cursor.fetchall()

# Get column names
column_names = [desc[0] for desc in cursor.description]

# Print in tabular format
print(tabulate(rows, headers=column_names, tablefmt="grid"))

# 1. SQL query to get customer_id, customer_name, and average balance amount

cursor.execute('''
CREATE TABLE BANK_ACCOUNTS1( Customer_id INT,
        Account_Number VARCHAR(19),
		    Account_type VARCHAR(25),
		    Balance_amount INT ,
			  Account_status VARCHAR(10),
        Relation_ship varchar(1) ) ;
''')
conn.commit()

def insert_customer1(customer_id,Account_Number,Account_type,Balance_amount,Account_status,Relation_ship):
  cursor.execute("INSERT INTO BANK_ACCOUNTS1(customer_id,Account_Number,Account_type,Balance_amount,Account_status, Relation_ship) Values(?,?,?,?,?,?)",(customer_id,Account_Number,Account_type,Balance_amount,Account_status, Relation_ship))
  conn.commit()

#insert
insert_customer1(123001, "4000-1956-3456",  "SAVINGS" , 200000 ,"ACTIVE","P");
insert_customer1(123001, "5000-1700-3456", "RECURRING DEPOSITS" ,9400000 ,"ACTIVE","S");
insert_customer1(123002, "4000-1956-2001",  "SAVINGS", 400000 ,"ACTIVE","P");
insert_customer1(123002, "5000-1700-5001",  "RECURRING DEPOSITS" ,7500000 ,"ACTIVE","S");
insert_customer1(123003, "4000-1956-2900",  "SAVINGS" ,750000,"INACTIVE","P");
insert_customer1(123004, "5000-1700-6091", "RECURRING DEPOSITS" ,7500000 ,"ACTIVE","S");
insert_customer1(123004, "4000-1956-3401",  "SAVINGS" , 655000 ,"ACTIVE","P");
insert_customer1(123005, "4000-1956-5102",  "SAVINGS" , 300000 ,"ACTIVE","P");
insert_customer1(123006, "4000-1956-5698",  "SAVINGS" , 455000 ,"ACTIVE" ,"P");
insert_customer1(123007, "5000-1700-9800",  "SAVINGS" , 355000 ,"ACTIVE" ,"P");
insert_customer1(123007, "4000-1956-9977",  "RECURRING DEPOSITS" , 7025000,"ACTIVE" ,"S");
insert_customer1(123007, "9000-1700-7777-4321",  "Credit Card"	,0  ,"INACTIVE", "P");
insert_customer1(123007, '5900-1900-9877-5543', "Add-on Credit Card" ,   0   ,"ACTIVE", "S");
insert_customer1(123008, "5000-1700-7755",  "SAVINGS"   	,0   	,"INACTIVE","P");
insert_customer1(123006, '5800-1700-9800-7755', "Credit Card"   ,0   	,"ACTIVE", "P");
insert_customer1(123006, '5890-1970-7706-8912', "Add-on Credit Card"   ,0   	,"ACTIVE", "S");

from tabulate import tabulate


# Fetch data
cursor.execute("SELECT * FROM BANK_ACCOUNTS1 ")
rows = cursor.fetchall()

# Get column names
column_names = [desc[0] for desc in cursor.description]

# Print in tabular format
print(tabulate(rows, headers=column_names, tablefmt="grid"))

# SQL query to get customer_id, customer_name, and average balance amount
query ='''
SELECT
    c.customer_id,
    c.customer_name,
    AVG(a.balance_amount) AS avg_balance
FROM BANK_CUSTOMERS1 c
LEFT JOIN BANK_ACCOUNTS1 a ON c.customer_id = a.customer_id
GROUP BY c.customer_id, c.customer_name
LIMIT 8;  --Show only 8 rows
'''


# Execute the query
cursor.execute(query)

# Fetch column names
columns = [desc[0] for desc in cursor.description]

# Fetch all results
results = cursor.fetchall()

# Print table headers
print("{:<12} {:<20} {:<15}".format(*columns))
print("-" * 50)

# Print each row in a properly formatted way
for row in results:
    print("{:<12} {:<20} {:<15.2f}".format(*row))  # Format avg_balance to 2 decimal places







# 2) Print customer_id , account_number and balance_amount , condition that if balance_amount is nil then assign transaction_amount  for account_type = "Credit Card"(4 Rows)

cursor.execute('''
CREATE TABLE Bank_Account_Details1(Customer_id INT,
                             	Account_Number VARCHAR(19),
                              	Account_type VARCHAR(25),
                           	    Balance_amount INT,
                               	Account_status VARCHAR(10),
                               	Relationship_type varchar(1) ) ;
''')
conn.commit()

def insert_details(customer_id,account_number,account_type,balance_amount,Account_status,Relationship_type):
  cursor.execute("insert into Bank_Account_Details1(customer_id,account_number,account_type,balance_amount,Account_status,Relationship_type) Values(?,?,?,?,?,?)",(customer_id,account_number,account_type,balance_amount,Account_status,Relationship_type))
  conn.commit()

insert_details(123001, "4000-1956-3456",  "SAVINGS" , 200000 ,"ACTIVE","P");
insert_details(123001, "5000-1700-3456", "RECURRING DEPOSITS" ,9400000 ,"ACTIVE","S");
insert_details(123002, "4000-1956-2001",  "SAVINGS", 400000 ,"ACTIVE","P");
insert_details(123002, "5000-1700-5001",  "RECURRING DEPOSITS" ,7500000 ,"ACTIVE","S");
insert_details(123003, "4000-1956-2900",  "SAVINGS" ,750000,"INACTIVE","P");
insert_details(123004, "5000-1700-6091", "RECURRING DEPOSITS" ,7500000 ,"ACTIVE","S");
insert_details(123004, "4000-1956-3401",  "SAVINGS" , 655000 ,"ACTIVE","P");
insert_details(123005, "4000-1956-5102",  "SAVINGS" , 300000 ,"ACTIVE","P");
insert_details(123006, "4000-1956-5698",  "SAVINGS" , 455000 ,"ACTIVE" ,"P");
insert_details(123007, "5000-1700-9800",  "SAVINGS" , 355000 ,"ACTIVE" ,"P");
insert_details(123007, "4000-1956-9977",  "RECURRING DEPOSITS" , 7025000,"ACTIVE" ,"S");
insert_details(123007, "9000-1700-7777-4321",  "Credit Card"	,0  ,"INACTIVE", "P");
insert_details(123007, '5900-1900-9877-5543', "Add-on Credit Card" ,   0   ,"ACTIVE", "S");
insert_details(123008, "5000-1700-7755",  "SAVINGS"   	,0   	,"INACTIVE","P");
insert_details(123006, '5800-1700-9800-7755', "Credit Card"   ,0   	,"ACTIVE", "P");
insert_details(123006, '5890-1970-7706-8912', "Add-on Credit Card"   ,0   	,"ACTIVE", "S");

from tabulate import tabulate


# Fetch data
cursor.execute("SELECT * FROM Bank_Account_Details1 ")
rows = cursor.fetchall()

# Get column names
column_names = [desc[0] for desc in cursor.description]

# Print in tabular format
print(tabulate(rows, headers=column_names, tablefmt="grid"))

cursor.execute('''
CREATE TABLE BANK_ACCOUNT_TRANSACTIONS1(
              	Account_Number VARCHAR(19),
              	Transaction_amount Decimal(18,2) ,
              	Transcation_channel VARCHAR(18) ,
             	Province varchar(3) ,
             	Transaction_Date Date) ;
''')
conn.commit()

def inser_trans(Account_Number,	Transaction_amount,Transcation_channel,Province,Transaction_Date):
  cursor.execute("INSERT INTO BANK_ACCOUNT_TRANSACTIONS1(Account_Number,Transaction_amount,Transcation_channel,Province,Transaction_Date) Values(?,?,?,?,?)",(Account_Number,	Transaction_amount,Transcation_channel,Province,Transaction_Date))
  conn.commit()

inser_trans("4000-1956-3456",  -2000, "ATM withdrawl" , "CA", "2020-01-13");
inser_trans("4000-1956-2001",  -4000, "POS-Walmart"   , "MN", "2020-02-14");
inser_trans("4000-1956-2001",  -1600, "UPI transfer"  , "MN", "2020-01-19");
inser_trans("4000-1956-2001",  -6000, "Bankers cheque", "CA", "2020-03-23");
inser_trans( "4000-1956-2001",  -3000, "Net banking"   , "CA", "2020-04-24");
inser_trans( "4000-1956-2001",  23000, "cheque deposit", "MN", "2020-03-15");
inser_trans( "5000-1700-6091",  40000, "ECS transfer"  , "NY", "2020-02-19");
inser_trans( "5000-1700-7791",  40000, "ECS transfer"  , "NY", "2020-02-19");
inser_trans( "4000-1956-3401",   8000, "Cash Deposit"  , "NY", "2020-01-19");
inser_trans( "4000-1956-5102",  -6500, "ATM withdrawal" , "NY", "2020-03-14");
inser_trans( "4000-1956-5698",  -9000, "Cash Deposit"  , "NY", "2020-03-27");
inser_trans( "4000-1956-9977",  50000, "ECS transfer"  , "NY", "2020-01-16");
inser_trans( "9000-1700-7777-4321",  -5000, "POS-Walmart", "NY", "2020-02-17");
inser_trans( "9000-1700-7777-4321",  -8000, "Shopping Cart", "MN", "2020-03-13");
inser_trans( "9000-1700-7777-4321",  -2500, "Shopping Cart", "MN", "2020-04-21");
inser_trans( "5800-1700-9800-7755", -9000, "POS-Walmart","MN", "2020-04-13");
inser_trans( '5890-1970-7706-8912', -11000, "Shopping Cart" , "NY" , "2020-03-12") ;

from tabulate import tabulate


# Fetch data
cursor.execute("SELECT * FROM BANK_ACCOUNT_TRANSACTIONS1 ")
rows = cursor.fetchall()

# Get column names
column_names = [desc[0] for desc in cursor.description]

# Print in tabular format
print(tabulate(rows, headers=column_names, tablefmt="grid"))

query = """
SELECT
    a.customer_id,
    a.account_number,
    COALESCE(a.balance_amount, t.transaction_amount) AS balance_amount
FROM BANK_Account_DetailS1 a
LEFT JOIN BANK_Account_transactions1 t ON a.account_number = t.account_number
WHERE a.account_type = 'Credit Card'
LIMIT 4;  -- Show only 4 rows
"""
result = pd.read_sql_query(query, conn)
print(tabulate(result, headers='keys', tablefmt='psql'))





# 3) Print account_number and balance_amount , transaction_amount,Transaction_Date from Bank_Account_Details
 # and bank_account_transaction for all the transactions occurred during march,2020 and april, 2020(12 Rows)

query="""SELECT
    b.account_number,
    b.balance_amount,
    t.transaction_amount,
    t.transaction_date
FROM
    Bank_Account_DetailS1 b
JOIN
    Bank_Account_Transactions1 t
    ON b.account_number = t.account_number
WHERE
    t.transaction_date BETWEEN '2020-03-01' AND '2020-04-30';"""
result = pd.read_sql_query(query, conn)
print(tabulate(result, headers='keys', tablefmt='psql'))





# 4) Print all of the customer id, account number,  balance_amount, transaction_amount , Transaction_Date  from bank_customer, Bank_Account_Details
#and bank_account_transaction tables where excluding all of their transactions in march, 2020  month (22 Rows)

query="""
SELECT
    c.customer_id,
    a.account_number,
    a.balance_amount,
    t.transaction_amount,
    t.transaction_date
FROM
    bank_customerS1 c
JOIN
    bank_account_detailS1 a
    ON c.customer_id = a.customer_id
JOIN
    bank_account_transactions1 t
    ON a.account_number = t.account_number
WHERE
    t.transaction_date NOT BETWEEN '2020-03-01' AND '2020-03-31';"""
result = pd.read_sql_query(query, conn)
print(tabulate(result, headers='keys', tablefmt='psql'))





# Question 5:
# 5) Print only the customer id, account_number, balance_amount,transaction_amount ,transaction_date who did transactions during the first quarter.
#Do not display the accounts if they have not done any transactions in the first quarter.(16 Rows)

query="""
SELECT
    c.customer_id,
    a.account_number,
    a.balance_amount,
    t.transaction_amount,
    t.transaction_date
FROM
    bank_customerS1 c
JOIN
    bank_account_detailS1 a
    ON c.customer_id = a.customer_id
JOIN
    bank_account_transactions1 t
    ON a.account_number = t.account_number
WHERE
    t.transaction_date BETWEEN '2020-01-01' AND '2020-03-31';"""
result = pd.read_sql_query(query, conn)
print(tabulate(result, headers='keys', tablefmt='psql'))





# Question 6:
# 6) Print account_number, Event and Customer_message from BANK_CUSTOMER_MESSAGES and Bank_Account_Details to display an “Adhoc"
# Event for all customers who have  “SAVINGS" account_type account.(8 Rows)

cursor.execute('''
CREATE TABLE BANK_CUSTOMER_MESSAGES1 (
              	Event VARCHAR(24),
              	Customer_message VARCHAR(75),
              	Notice_delivery_mode VARCHAR(15)) ;
''')
conn.commit()

cursor.execute("ALTER TABLE BANK_CUSTOMER_MESSAGES1 ADD COLUMN account_number INT;")
conn.commit()

def msg(account_number, Event, Customer_message, Notice_delivery_mode):
    cursor.execute(
        "INSERT INTO BANK_CUSTOMER_MESSAGES1(account_number, Event, Customer_message, Notice_delivery_mode) VALUES (?, ?,?,?)",
        (account_number, Event, Customer_message, Notice_delivery_mode)
    )
    conn.commit()

msg(1001, "Adhoc", "All Banks are closed due to announcement of National strike", "mobile")
msg(1002, "Transaction Limit", "Only limited withdrawals per card are allowed from ATM machines", "mobile")

from tabulate import tabulate


# Fetch data
cursor.execute("SELECT * FROM BANK_CUSTOMER_MESSAGES1 ")
rows = cursor.fetchall()

# Get column names
column_names = [desc[0] for desc in cursor.description]

# Print in tabular format
print(tabulate(rows, headers=column_names, tablefmt="grid"))

query="""
SELECT
    m.account_number AS message_account_number,
    m.event,
    m.customer_message
FROM
    bank_customer_messages1 m
LEFT JOIN
    bank_account_details1 a
    ON a.customer_id = m.account_number  -- Joining on customer_id instead of account_number based on data
WHERE
    m.event = 'Adhoc' AND (a.account_type = 'SAVINGS' OR a.account_type IS NULL);"""

result = pd.read_sql_query(query, conn)
print(tabulate(result, headers='keys', tablefmt='psql'))







# Question 7:
# 7) Print all Customer_id, Account_Number, Account_type, and display deducted balance_amount by  subtracting only negative transaction_amounts for Relationship_type ="P" ( P - means  Primary , S - means Secondary ) .(27 Rows)

query="""
SELECT
    c.customer_id,
    a.account_number,
    a.account_type,
    a.balance_amount + COALESCE(SUM(t.transaction_amount), 0) AS deducted_balance_amount
FROM
    bank_customers1 c
JOIN
    bank_account_details1 a
    ON c.customer_id = a.customer_id
JOIN
    bank_account_transactions1 t
    ON a.account_number = t.account_number
WHERE
    a.relationship_type = 'P'
    AND t.transaction_amount < 0   -- only negative transactions
GROUP BY
    c.customer_id, a.account_number, a.account_type, a.balance_amount;"""



result = pd.read_sql_query(query, conn)
print(tabulate(result, headers='keys', tablefmt='psql'))





# Question 8:
# a) Display records of All Accounts , their Account_types, the transaction amount

query="""
SELECT
    a.account_number,
    a.account_type,
    t.transaction_amount
FROM
    bank_account_details1 a
LEFT JOIN
    bank_account_transactions1 t
    ON a.account_number = t.account_number;"""

result = pd.read_sql_query(query, conn)
print(tabulate(result, headers='keys', tablefmt='psql'))

# b) Along with first step, Display other columns with corresponding linking account number, account types (15 Rows)
query="""
SELECT
    c.customer_id,
    c.customer_name,
    a.account_number,
    a.account_type,
    a.balance_amount,
    t.transaction_amount,
    t.transaction_date
FROM
    bank_customers1 c
JOIN
    bank_account_details1 a
    ON c.customer_id = a.customer_id
LEFT JOIN
    bank_account_transactions1 t
    ON a.account_number = t.account_number;"""

result = pd.read_sql_query(query, conn)
print(tabulate(result, headers='keys', tablefmt='psql'))





# Question 9:
# a) Display records of All Accounts , their Account_types, the transaction amount.
# b) Along with first step, Display other columns with corresponding linking account number, account types
# c) After retrieving all records of accounts and their linked accounts, display the   transaction amount of accounts appeared  in another column.(26 Rows)

query="""
SELECT
    a.account_number,
    a.account_type,
    t.transaction_amount
FROM
    bank_account_details1 a
JOIN
    bank_account_transactions1 t
    ON a.account_number = t.account_number;"""


result = pd.read_sql_query(query, conn)
print(tabulate(result, headers='keys', tablefmt='psql'))

cursor.execute('''
CREATE TABLE Bank_Account_Relationship_Details
                             	( Customer_id INT,
								Account_Number VARCHAR(19),
                            	Account_type VARCHAR(25),
                             	Linking_Account_Number VARCHAR(19));
''')
conn.commit()

def rel(Customer_id,Account_Number,	Account_type,	Linking_Account_Number):
  cursor.execute("INSERT INTO Bank_Account_Relationship_Details(Customer_id,Account_Number,	Account_type,	Linking_Account_Number) VALUES(?,?,?,?)",(Customer_id,Account_Number,	Account_type,	Linking_Account_Number))
  conn.commit()

rel(123001, "4000-1956-3456",  "SAVINGS" , "");
rel(123001, "5000-1700-3456",  "RECURRING DEPOSITS" , "4000-1956-3456");
rel(123002, "4000-1956-2001",  "SAVINGS" , "" );
rel(123002, "5000-1700-5001",  "RECURRING DEPOSITS" , "4000-1956-2001" );
rel(123003, "4000-1956-2900",  "SAVINGS" , "" );
rel(123004, "5000-1700-6091",  "RECURRING DEPOSITS" , "4000-1956-2900" );
rel(123004, "5000-1700-7791",  "RECURRING DEPOSITS" , "4000-1956-2900" );
rel(123007, "5000-1700-9800",  "SAVINGS" , "" );
rel(123007, "4000-1956-9977",  "RECURRING DEPOSITS" , "5000-1700-9800" );
rel(123008, "9000-1700-7777-4321",  "Credit Card" , "5000-1700-9800" );
rel(123009, '5900-1900-9877-5543', 'Add-on Credit Card', '9000-1700-7777-4321' );
rel(123010, '5800-1700-9800-7755', 'Credit Card', '4000-1956-5698' );
rel(123011, '5890-1970-7706-8912', 'Add-on Credit Card', '5800-1700-9800-7755' );

from tabulate import tabulate


# Fetch data
cursor.execute("SELECT * FROM Bank_Account_Relationship_Details ")
rows = cursor.fetchall()

# Get column names
column_names = [desc[0] for desc in cursor.description]

# Print in tabular format
print(tabulate(rows, headers=column_names, tablefmt="grid"))

query="""
SELECT
    a.account_number,
    a.account_type,
    t.transaction_amount,
    r.linking_account_number,
    a2.account_type AS linked_account_type
FROM
    bank_account_details1 a
JOIN
    bank_account_transactions1 t
    ON a.account_number = t.account_number
JOIN
    Bank_Account_Relationship_Details r
    ON a.account_number = r.account_number
JOIN
    bank_account_details1 a2
    ON r.linking_account_number = a2.account_number;
"""

result = pd.read_sql_query(query, conn)
print(tabulate(result, headers='keys', tablefmt='psql'))





# Question 10:
# 10) Display all saving account holders have “Add-on Credit Cards" and “Credit cards" (3 Rows)

query="""
SELECT
    DISTINCT bad.customer_id,
    bad.account_number AS savings_account_number,
    bad.account_type AS savings_account_type,
    bad2.account_type AS linked_card_type
FROM
    bank_account_details1 bad
JOIN
    Bank_Account_Relationship_Details bard ON bad.account_number = bard.Linking_Account_Number
JOIN
    bank_account_details1 bad2 ON bard.Account_Number = bad2.account_number
WHERE
    bad.account_type = 'SAVINGS'
    AND bad2.account_type IN ('Credit Card', 'Add-on Credit Card');
"""

result = pd.read_sql_query(query, conn)
print(tabulate(result, headers='keys', tablefmt='psql'))

query="""
SELECT
    DISTINCT bad.customer_id,
    bad.account_number AS savings_account_number,
    bad.account_type AS savings_account_type,
    bad2.account_type AS linked_card_type
FROM
    bank_account_details1 bad
JOIN
    Bank_Account_Relationship_Details bard ON bad.account_number = bard.Linking_Account_Number
JOIN
    bank_account_details1 bad2 ON bard.Account_Number = bad2.account_number
WHERE
    bad.account_type = 'SAVINGS'
    AND bad2.account_type IN ('Credit Card', 'Add-on Credit Card');
"""
result = pd.read_sql_query(query, conn)
print(tabulate(result, headers='keys', tablefmt='psql'))





# 11)  Display  records of “SAVINGS” account linked with “Credit cards" account_type and its credit
# aggregate sum of transaction amount. (1 Row)
# Ref: Check linking relationship in bank_transaction_relationship_details.
        # Check transaction_amount in bank_account_transaction

from tabulate import tabulate


# Fetch data
cursor.execute("SELECT * FROM Bank_Account_Relationship_Details ")
rows = cursor.fetchall()

# Get column names
column_names = [desc[0] for desc in cursor.description]

# Print in tabular format
print(tabulate(rows, headers=column_names, tablefmt="grid"))

query="""
SELECT
    bas.account_number AS Savings_Account_Number,
    bas.account_type AS Savings_Account_Type,
    bard.Account_Number AS Linked_Card_Number,
    bad.Account_Type AS Linked_Card_Type,
    SUM(bat.Transaction_Amount) AS Total_Transaction_Amount
FROM
    Bank_Account_Relationship_Details bard
JOIN
    bank_account_details1 bas ON bard.Linking_Account_Number = bas.account_number
JOIN
    bank_account_details1 bad ON bard.Account_Number = bad.account_number
LEFT JOIN
    bank_account_transactions1 bat ON bard.Account_Number = bat.Account_Number
WHERE
    bas.Account_Type = 'SAVINGS'
    AND bad.Account_Type IN ('Credit Card', 'Add-on Credit Card')
GROUP BY
    bas.account_number, bas.account_type, bard.Account_Number, bad.Account_Type;
"""

result = pd.read_sql_query(query, conn)
print(tabulate(result, headers='keys', tablefmt='psql'))

